# Generated by Django 2.2.2 on 2019-06-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='choice',
            order_with_respect_to='votes',
        ),
    ]
