# Generated by Django 2.2.2 on 2019-06-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190612_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-votes']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='choice',
            order_with_respect_to=None,
        ),
    ]
