# Generated by Django 2.2.2 on 2019-06-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_vote_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-choice_text']},
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='voter',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
