# Generated by Django 2.2.2 on 2019-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190612_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='nr_of_votes',
            field=models.IntegerField(default=1),
        ),
    ]
